### ISSUE TITLE
Изучить возможности API John Deer 

### ISSUE THREAD

**Issue by psilon2000** [eko-point/plant-driver-boilerplate#4]
Изучить возможности API в плане
1. Получения данных о локации трактора (есть данные по точности)
2. Получения данных с исо/кан шины (уровень топлива, состояние зажигания и т.д.)
3. Как оперативно обновляются данные. Есть ли ограничения по количеству запросов  и т.п.
Если нужна авторизация или еще что-то просьба сразу сообщить. 
https://developer.deere.com

**Comment by CliffordSimak** [comment]
**1) Локация - стандарт JDLink ™ Machine Data Telematics.**

Методы получения координат:
- View the last known locations of machines in the fleet.
- View the last known locations of machines in the fleet, within a given timeframe.

Точность координат в ответе:
- Latitude: _−90,000 000° to +90,000 000°_
- Longitude: _−180,000 000° to +180,000 000°_

**2) Уровень топлива -  стандарт JDLink ™ Machine Data Telematics.**

Методы  получения уровня топлива:
- View the percentage of fuel remaining in the fuel tank of the machine.
- View the percentage of fuel remaining in the fuel tank of the machine, with measurements taken within a given period of time.

Точность уровня топлива в ответе:
- _56.40 %_

**Состояние зажигания  -  стандарт JDLink ™ Machine Data Telematics.**

Методы  получения состояния зажигания:
- Retrieve a list of cumulative operating hours, beginning with a chosen page.
- View the lifetime total cumulative idle hours of a machine, as measured within a given timeframe.

Точность ответа:
_354.90 h._

**3) Обновление данных** 
Данные можно получить _сразу_ оперируя входящими данными. Локация и горючее доступны в течение последних 24 часов. На какой-то страницу прочел, что данные могут идти долго и следует установить timeout запроса на 10 минут. Запись про ограничение количества запросов не увидел.

Для использования перечисленных методов требуется запрос на предоставление полного функционала API. Я заполнил форму запроса к API, пока жду.

**Comment by psilon2000** [comment]
Issue moved to [eko-point/plant-john-deer #4](https://github.com/eko-point/plant-john-deer/issues/4) via [**ZenHub**](https://www.zenhub.com/)
